### ISSUE TITLE
[1.20.1] Incompatibility with JER

### ISSUE THREAD

**Issue by ffuentesm** [Prismwork/EMITrades#19]
EMI: 1.0.19+1.20.1 -forge
EMI Trade: 1.2.0+mc1.20.1
JER: 1.4.0.238
JEI: 15.2.027

From what I saw, EMI allows use alongside JEI for recipe compatibility. 
So I also use JER for the resource and mob drop information. 
That also adds Trading info for the villagers. I liked the EMI Trade UI way better, but for some reason, EMI Trade crashes the game if JER is installed.

**Comment by moechakucha** [comment]
hmm, weird
logs?
