### ISSUE TITLE
Any  plans on expanding EMI to cover other utilities? 

### ISSUE THREAD

**Issue by ffuentesm** [Prismwork/EMITrades#20]
I have been loving this EMI add-on for trades, very efficient, and I am using it over JER trade menu. 
So I was wondering if you have plans on making other EMI add-ons that cover other areas, such as loot drops, or ore mining levels.
I mostly rely on JER for that, but not many mods make it compatible with the Ore level function.

**Comment by moechakucha** [comment]
there are already addons for loots (EMI Loot) and ores (EMI Ores).
