### ISSUE TITLE
[Feature Request] Could you add a Pigling Bartering Tab?

### ISSUE THREAD

**Issue by ffuentesm** [Prismwork/EMITrades#22]
I noticed that there are no Bartering tabs in either EMI, JER or JEI, and I think would be nice to see which items and the percentage they drop from a bartering, as many mods add custom items to the bartering list and I would love to be able to see what I can get.

**Comment by Disketaa** [comment]
+1

**Comment by moechakucha** [comment]
I don't think this is doable on my side. Piglin bartering is basically loot tables, which are handled on server side and thus unobtainable for client sided mods like this. You may have a look at EMI Loot.
