### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by IFedor-F** [Prismwork/EMITrades#8]
Please, update mod to new version minecraft

**Comment by moechakucha** [comment]
Resolved in https://github.com/Prismwork/EMITrades/commit/6b39b8209239658ca1330bec771716d6397fc663

**Comment by LemonShaped** [comment]
@Flamarine are you planning on uploading it to modrinth? The build from [here](https://github.com/Prismwork/EMITrades/actions/runs/5487870094) seems to work.
And for EMIEffect as well.
